### ISSUE TITLE
conn.Ping() throwing nil pointer errors 

### ISSUE THREAD

**Issue by radhianamri** [lib/pq#1059]
Hi, I am intermittently getting the below error when calling conn.Ping() which is being called periodically. The rows object returned by .simpleQuery() is getting nil. https://github.com/lib/pq/blob/master/conn_go18.go#L95
```
2021/09/28 12:20:04 [16139] panic: runtime error: invalid memory address or nil pointer dereference
2021/09/28 12:20:04 [16139] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9efe6f]
2021/09/28 12:20:04 [16139]
2021/09/28 12:20:04 [16139] goroutine 44 [running]:
2021/09/28 12:20:04 [16139] github.com/XXXX/XX/vendor/github.com/lib/pq.(*rows).Close(0x0, 0x0, 0x0)
2021/09/28 12:20:04 [16139]         /share/dpkg-build/cm-build/src/github.com/XXXX/XX/vendor/github.com/lib/pq/conn.go:1494 +0x3f
2021/09/28 12:20:04 [16139] github.com/XXXX/XX/vendor/github.com/lib/pq.(*conn).Ping(0xc00284cdc0, 0x187efa0, 0xc002a1a6c0, 0x0, 0x0)
2021/09/28 12:20:04 [16139]         /share/dpkg-build/cm-build/src/github.com/XXXX/XX/vendor/github.com/lib/pq/conn_go18.go:87 +0xf6
2021/09/28 12:20:04 [16139] database/sql.(*DB).pingDC.func1()
2021/09/28 12:20:04 [16139]         /home/buildbot/.gvm/gos/go1.14.4/src/database/sql/sql.go:768 +0x4a
2021/09/28 12:20:04 [16139] database/sql.withLock(0x18660c0, 0xc001f2a080, 0xc003d83c10)
2021/09/28 12:20:04 [16139]         /home/buildbot/.gvm/gos/go1.14.4/src/database/sql/sql.go:3184 +0x69
2021/09/28 12:20:04 [16139] database/sql.(*DB).pingDC(0xc0001aa240, 0x187efa0, 0xc002a1a6c0, 0xc001f2a080, 0xc003d83cc0, 0x0, 0x0)
2021/09/28 12:20:04 [16139]         /home/buildbot/.gvm/gos/go1.14.4/src/database/sql/sql.go:767 +0x11b
2021/09/28 12:20:04 [16139] database/sql.(*DB).PingContext(0xc0001aa240, 0x187efa0, 0xc002a1a6c0, 0x187efa0, 0xc002a1a6c0)
2021/09/28 12:20:04 [16139]         /home/buildbot/.gvm/gos/go1.14.4/src/database/sql/sql.go:794 +0x170
```
Would it be possible to check if rows is not nil before closing it in this line?
https://github.com/lib/pq/blob/master/conn_go18.go#L99

Seems related to this as well https://github.com/lib/pq/issues/1019

**Comment by Yowgf** [comment]
I had exactly the same problem.

**Comment by JuchangGit** [comment]
I have exactly the same problem

**Comment by arp242** [comment]
The problem is conn.simpleQuery() can return nil, nil (and by extension, so can conn.query()). That's probably what should be fixed instead of checking whether rows is non-nil – I saw another issue/panic with the same root cause earlier.

**Comment by Yowgf** [comment]
I tried reproducing the issue and was unable to do so when running against postgres 15, 18. I also tested against pgbuster + postgres and nothing. I think at the time I got the error the server was hosted in AWS RDS, but I didn't have time to test with AWS RDS this time.

Based on the code in simpleQuery(), the only way this condition would be triggered was if the loop only ever entered the 'Z' condition before exiting the function. Maybe this PR would help (feel free to close it if it doesn't make sense): https://github.com/lib/pq/pull/1230

@arp242
