### ISSUE TITLE
Bad conninfo causes a panic, not a returned error

### ISSUE THREAD

**Issue by Omortis** [lib/pq#394]
Hello!

When opening a db connection via sql.Open:

```golang
db, err := sql.Open("postgres", dbconn)
```
if there are any errors due to bad connection parameters a panic is created, where sql.Open should simply return the error generated.

Is this expected behavior?

Thanks,

John

**Comment by johto** [comment]
> Is this expected behavior?

Probably not.  What's the exact panic, and the exact conn info string?

**Comment by Omortis** [comment]
The conn info string contains the standard user, host, dbname and password fields and it all works like a charm. Unless I intentionally send the wrong password, in which case I get:

```
firx:golang johnnyb$ go build -o wsbc.v4
firx:golang johnnyb$ ./wsbc.v4 
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xb69b8]

goroutine 1 [running]:
database/sql.(*Stmt).Close(0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1518 +0x2a8
database/sql.(*Stmt).Query(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1433 +0x70a
main.syncTapList(0x314bb0, 0x4, 0x0, 0x0)
	/Users/johnnyb/Projects/repos/wsbc.go/golang/taplist.go:64 +0x342
main.init·2()
	/Users/johnnyb/Projects/repos/wsbc.go/golang/main.go:28 +0x34
main.init()
	/Users/johnnyb/Projects/repos/wsbc.go/golang/winelist.go:99 +0x74

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20802a1e0)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
firx:golang johnnyb$ 
```

This is on OSX. I can attempt to recreate on Debian if it will help.

Thanks!

John

**Comment by uhoh-itsmaciek** [comment]
Can you show us what your test program looks like? The stack trace doesn't seem to match what you've described (note the panic is *not* from `Open`).

**Comment by Omortis** [comment]
Hmm, no, I was not reading the panic correctly. I will create a much smaller test and see if I can reproduce the error. Should have though of that earlier. I will come back and add  to or close this issue in a bit.

Thanks,

John

**Comment by Omortis** [comment]
The short code snipped below generates the same panic on OSX and Linux. Am I coding something incorrectly? Note that I can recover the panic if needed, I just want to know why I would need to. I have only redacted some of the conninfo.

```go
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/lib/pq"
)

func main() {
	tap_query := "select brand_name from brands where brand_code=18"
	dbconn := "user=johnnyb dbname=db host=1.2.3.4 password=abcdefghi"

	var prepared *sql.Stmt

	db, err := sql.Open("postgres", dbconn)
	if err != nil {
		fmt.Printf("sql.Open failure - err: %v", err)
	}

	prepared, err = db.Prepare(tap_query)
	defer prepared.Close()

	rows, err := prepared.Query()
	defer rows.Close()

	if err != nil {
		fmt.Printf("prepared.Query() failed - err: %v", err)
	}

	for rows.Next() {
		var brand_name string
		if err := rows.Scan(&brand_name); err != nil {
			fmt.Printf("rows.Scan failed - err: %v", err)
		} else {
			var name string
			name = brand_name
			fmt.Printf("\tname = %s\n", name)
		}
	}
	if err := rows.Err(); err != nil {
		fmt.Printf("rows.Err is not nil - err: %v", err)
	}
}
```

On Linux and OSX:

```
firx:dbpanic johnnyb$ go build
firx:dbpanic johnnyb$ ./dbpanic 
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4be98]

goroutine 1 [running]:
database/sql.(*Stmt).Close(0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1518 +0x2a8
database/sql.(*Stmt).Query(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1433 +0x70a
main.main()
	/Users/johnnyb/Projects/dbpanic/dbpanic.go:23 +0x211

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208054000)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by cbandy** [comment]
Check the `err` on L20 from `db.Prepare `.

**Comment by Omortis** [comment]
Ouch! Nice catch. Still panics, but it's because the function does not return after the conn error and instead tries to Query() the prepared statement. Ironically I was fixing these returns when I hit the panic...

Sorry for the static folks and thanks for the help.

John
