### ISSUE TITLE
Panic when loading pgpass file

### ISSUE THREAD

**Issue by paulbellamy** [lib/pq#474]
Relevant bit of the stacktrace below
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xe5 pc=0x7f67e025b878]

runtime stack:
runtime.throw(0xc08f20, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 25 [syscall, locked to thread]:
runtime.cgocall(0x8a59c0, 0xc8200e6950, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc8200e68f8 sp=0xc8200e68c8
os/user._Cfunc_mygetpwuid_r(0x0, 0xc8201c2db0, 0x7f67d0000a10, 0x400, 0xc820020258, 0x0)
	??:0 +0x44 fp=0xc8200e6950 sp=0xc8200e68f8
os/user.lookupUnix(0x0, 0x0, 0x0, 0xb4a900, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup_unix.go:95 +0xcd8 fp=0xc8200e6ae8 sp=0xc8200e6950
os/user.current(0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup_unix.go:38 +0x42 fp=0xc8200e6b28 sp=0xc8200e6ae8
os/user.Current(0xb4a9b0, 0x0, 0x0)
	/usr/local/go/src/os/user/lookup.go:9 +0x24 fp=0xc8200e6b48 sp=0xc8200e6b28
github.com/weaveworks/scope/vendor/github.com/lib/pq.(*conn).handlePgpass(0xc820160f00, 0xc8201c2c90)
	/go/src/github.com/weaveworks/scope/vendor/github.com/lib/pq/conn.go:156 +0xd4 fp=0xc8200e6de8 sp=0xc8200e6b48
github.com/weaveworks/scope/vendor/github.com/lib/pq.DialOpen(0x7f67e0c68d80, 0x10d7448, 0xc82000fc70, 0x50, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/lib/pq/conn.go:311 +0xccc fp=0xc8200e7340 sp=0xc8200e6de8
github.com/weaveworks/scope/vendor/github.com/lib/pq.Open(0x7ffcccb6fc4b, 0x4a, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/lib/pq/conn.go:229 +0x9e fp=0xc8200e7388 sp=0xc8200e7340
github.com/weaveworks/scope/vendor/github.com/lib/pq.(*drv).Open(0x10d7448, 0x7ffcccb6fc4b, 0x4a, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/scope/vendor/github.com/lib/pq/conn.go:40 +0x43 fp=0xc8200e73c0 sp=0xc8200e7388
database/sql.(*DB).conn(0xc8200b0790, 0xc81fff1c01, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:821 +0x59d fp=0xc8200e7560 sp=0xc8200e73c0
database/sql.(*DB).query(0xc8200b0790, 0xc69560, 0x102, 0xc8200e7820, 0x1, 0x1, 0xc820160c01, 0x1, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1073 +0x46 fp=0xc8200e75e0 sp=0xc8200e7560
database/sql.(*DB).Query(0xc8200b0790, 0xc69560, 0x102, 0xc8200e7820, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1061 +0xa3 fp=0xc8200e7658 sp=0xc8200e75e0
database/sql.(*DB).QueryRow(0xc8200b0790, 0xc69560, 0x102, 0xc8200e7820, 0x1, 0x1, 0x1)
...
```

Seems like `os/user.Current()` us panicking, but I can't replicate it outside of using libpq on debian:stretch as root.

Is lib/pq doing anything odd with this? Or maybe this is an issue in `os/user`?

**Comment by ajvb** [comment]
@paulbellamy Would you mind posting a snippet to replicate?

**Comment by paulbellamy** [comment]
Hmm. Can't seem to replicate it now. I'll re-open this if I manage to reproduce it again.
