### ISSUE TITLE
Tests Are Failing

### ISSUE THREAD

**Issue by drasko** [lib/pq#518]
```
drasko@Lenin:~/go/src/github.com/mainflux/mainflux/vendor/github.com/lib/pq$ go test -v ./...
=== RUN   TestParseArray
--- PASS: TestParseArray (0.00s)
=== RUN   TestParseArrayError
--- PASS: TestParseArrayError (0.00s)
=== RUN   TestArrayScanner
--- PASS: TestArrayScanner (0.00s)
=== RUN   TestArrayValuer
--- PASS: TestArrayValuer (0.00s)
=== RUN   TestBoolArrayScanUnsupported
--- PASS: TestBoolArrayScanUnsupported (0.00s)
=== RUN   TestBoolArrayScanBytes
--- PASS: TestBoolArrayScanBytes (0.00s)
=== RUN   TestBoolArrayScanString
--- PASS: TestBoolArrayScanString (0.00s)
=== RUN   TestBoolArrayScanError
--- PASS: TestBoolArrayScanError (0.00s)
=== RUN   TestBoolArrayValue
--- PASS: TestBoolArrayValue (0.00s)
=== RUN   TestByteaArrayScanUnsupported
--- PASS: TestByteaArrayScanUnsupported (0.00s)
=== RUN   TestByteaArrayScanBytes
--- PASS: TestByteaArrayScanBytes (0.00s)
=== RUN   TestByteaArrayScanString
--- PASS: TestByteaArrayScanString (0.00s)
=== RUN   TestByteaArrayScanError
--- PASS: TestByteaArrayScanError (0.00s)
=== RUN   TestByteaArrayValue
--- PASS: TestByteaArrayValue (0.00s)
=== RUN   TestFloat64ArrayScanUnsupported
--- PASS: TestFloat64ArrayScanUnsupported (0.00s)
=== RUN   TestFloat64ArrayScanBytes
--- PASS: TestFloat64ArrayScanBytes (0.00s)
=== RUN   TestFloat64ArrayScanString
--- PASS: TestFloat64ArrayScanString (0.00s)
=== RUN   TestFloat64ArrayScanError
--- PASS: TestFloat64ArrayScanError (0.00s)
=== RUN   TestFloat64ArrayValue
--- PASS: TestFloat64ArrayValue (0.00s)
=== RUN   TestInt64ArrayScanUnsupported
--- PASS: TestInt64ArrayScanUnsupported (0.00s)
=== RUN   TestInt64ArrayScanBytes
--- PASS: TestInt64ArrayScanBytes (0.00s)
=== RUN   TestInt64ArrayScanString
--- PASS: TestInt64ArrayScanString (0.00s)
=== RUN   TestInt64ArrayScanError
--- PASS: TestInt64ArrayScanError (0.00s)
=== RUN   TestInt64ArrayValue
--- PASS: TestInt64ArrayValue (0.00s)
=== RUN   TestStringArrayScanUnsupported
--- PASS: TestStringArrayScanUnsupported (0.00s)
=== RUN   TestStringArrayScanBytes
--- PASS: TestStringArrayScanBytes (0.00s)
=== RUN   TestStringArrayScanString
--- PASS: TestStringArrayScanString (0.00s)
=== RUN   TestStringArrayScanError
--- PASS: TestStringArrayScanError (0.00s)
=== RUN   TestStringArrayValue
--- PASS: TestStringArrayValue (0.00s)
=== RUN   TestGenericArrayScanUnsupported
--- PASS: TestGenericArrayScanUnsupported (0.00s)
=== RUN   TestGenericArrayScanScannerArrayBytes
--- PASS: TestGenericArrayScanScannerArrayBytes (0.00s)
=== RUN   TestGenericArrayScanScannerArrayString
--- PASS: TestGenericArrayScanScannerArrayString (0.00s)
=== RUN   TestGenericArrayScanScannerSliceBytes
--- PASS: TestGenericArrayScanScannerSliceBytes (0.00s)
=== RUN   TestGenericArrayScanScannerSliceString
--- PASS: TestGenericArrayScanScannerSliceString (0.00s)
=== RUN   TestGenericArrayScanDelimiter
--- PASS: TestGenericArrayScanDelimiter (0.00s)
=== RUN   TestGenericArrayScanErrors
--- PASS: TestGenericArrayScanErrors (0.00s)
=== RUN   TestGenericArrayValueUnsupported
--- PASS: TestGenericArrayValueUnsupported (0.00s)
=== RUN   TestGenericArrayValue
--- PASS: TestGenericArrayValue (0.00s)
=== RUN   TestGenericArrayValueErrors
--- PASS: TestGenericArrayValueErrors (0.00s)
=== RUN   TestArrayScanBackend
--- FAIL: TestArrayScanBackend (0.01s)
	array_test.go:1125: Expected no error when scanning ARRAY[true, false] into *pq.BoolArray, got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1128: Expected &[true false] when scanning ARRAY[true, false] into *pq.BoolArray, got &[]
	array_test.go:1125: Expected no error when scanning ARRAY[E'\\xdead', E'\\xbeef'] into *pq.ByteaArray, got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1128: Expected &[[222 173] [190 239]] when scanning ARRAY[E'\\xdead', E'\\xbeef'] into *pq.ByteaArray, got &[]
	array_test.go:1125: Expected no error when scanning ARRAY[1.2, 3.4] into *pq.Float64Array, got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1128: Expected &[1.2 3.4] when scanning ARRAY[1.2, 3.4] into *pq.Float64Array, got &[]
	array_test.go:1125: Expected no error when scanning ARRAY[1, 2, 3] into *pq.Int64Array, got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1128: Expected &[1 2 3] when scanning ARRAY[1, 2, 3] into *pq.Int64Array, got &[]
	array_test.go:1125: Expected no error when scanning ARRAY['a', E'\\b', 'c"', 'd,e'] into *pq.StringArray, got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1128: Expected &[a \b c" d,e] when scanning ARRAY['a', E'\\b', 'c"', 'd,e'] into *pq.StringArray, got &[]
=== RUN   TestArrayValueBackend
--- FAIL: TestArrayValueBackend (0.00s)
	array_test.go:1150: Expected [true false] to equal ARRAY[true, false], got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1150: Expected [[222 173] [190 239]] to equal ARRAY[E'\\xdead', E'\\xbeef'], got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1150: Expected [1.2 3.4] to equal ARRAY[1.2, 3.4], got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1150: Expected [1 2 3] to equal ARRAY[1, 2, 3], got dial tcp [::1]:5432: getsockopt: connection refused
	array_test.go:1150: Expected [a \b c" d,e] to equal ARRAY['a', E'\\b', 'c"', 'd,e'], got dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestDecodeBool
--- FAIL: TestDecodeBool (0.00s)
	bench_test.go:352: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestReconnect
--- FAIL: TestReconnect (0.00s)
	conn_test.go:72: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCommitInFailedTransaction
--- FAIL: TestCommitInFailedTransaction (0.00s)
	conn_test.go:106: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestOpenURL
--- FAIL: TestOpenURL (0.00s)
	conn_test.go:130: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestPgpass
--- SKIP: TestPgpass (0.00s)
	conn_test.go:142: not running under Travis, skipping pgpass tests
=== RUN   TestExec
--- FAIL: TestExec (0.00s)
	conn_test.go:233: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestStatment
--- FAIL: TestStatment (0.00s)
	conn_test.go:281: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestRowsCloseBeforeDone
--- FAIL: TestRowsCloseBeforeDone (0.00s)
	conn_test.go:340: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestParameterCountMismatch
--- FAIL: TestParameterCountMismatch (0.00s)
	conn_test.go:369: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestEmptyQuery
--- FAIL: TestEmptyQuery (0.00s)
	conn_test.go:390: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestEmptyResultSetColumns
--- FAIL: TestEmptyResultSetColumns (0.00s)
	conn_test.go:456: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestEncodeDecode
--- FAIL: TestEncodeDecode (0.00s)
	conn_test.go:528: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestNoData
--- FAIL: TestNoData (0.00s)
	conn_test.go:589: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestErrorDuringStartup
--- FAIL: TestErrorDuringStartup (0.00s)
	conn_test.go:633: expected Error, got &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc4200fb620), Err:(*os.SyscallError)(0xc42016d280)}
=== RUN   TestBadConn
--- PASS: TestBadConn (0.00s)
=== RUN   TestErrorOnExec
--- FAIL: TestErrorOnExec (0.00s)
	conn_test.go:674: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestErrorOnQuery
--- FAIL: TestErrorOnQuery (0.00s)
	conn_test.go:702: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestErrorOnQueryRowSimpleQuery
--- FAIL: TestErrorOnQueryRowSimpleQuery (0.00s)
	conn_test.go:730: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestQueryRowBugWorkaround
--- FAIL: TestQueryRowBugWorkaround (0.00s)
	conn_test.go:761: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestSimpleQuery
--- FAIL: TestSimpleQuery (0.00s)
	conn_test.go:857: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestBindError
--- FAIL: TestBindError (0.00s)
	conn_test.go:872: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestParseErrorInExtendedQuery
--- FAIL: TestParseErrorInExtendedQuery (0.00s)
	conn_test.go:899: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestReturning
--- FAIL: TestReturning (0.00s)
	conn_test.go:911: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestIssue186
--- FAIL: TestIssue186 (0.00s)
	conn_test.go:947: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestIssue196
--- FAIL: TestIssue196 (0.00s)
	conn_test.go:994: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestIssue282
--- FAIL: TestIssue282 (0.00s)
	conn_test.go:1016: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestReadFloatPrecision
--- FAIL: TestReadFloatPrecision (0.00s)
	conn_test.go:1032: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestXactMultiStmt
--- SKIP: TestXactMultiStmt (0.00s)
	conn_test.go:1045: Skipping failing test
=== RUN   TestParseEnviron
--- PASS: TestParseEnviron (0.00s)
=== RUN   TestParseComplete
--- PASS: TestParseComplete (0.00s)
=== RUN   TestExecerInterface
--- PASS: TestExecerInterface (0.00s)
=== RUN   TestNullAfterNonNull
--- FAIL: TestNullAfterNonNull (0.00s)
	conn_test.go:1179: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   Test64BitErrorChecking
--- FAIL: Test64BitErrorChecking (0.00s)
	conn_test.go:1234: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCommit
--- FAIL: TestCommit (0.00s)
	conn_test.go:1249: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestErrorClass
--- FAIL: TestErrorClass (0.00s)
	conn_test.go:1285: expected *pq.Error, got &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc42019e600), Err:(*os.SyscallError)(0xc4201a4a20)}
=== RUN   TestParseOpts
--- PASS: TestParseOpts (0.00s)
=== RUN   TestRuntimeParameters
--- FAIL: TestRuntimeParameters (0.00s)
	conn_test.go:1405: options='-c search_path=pqgotest': unexpected error: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestIsUTF8
--- PASS: TestIsUTF8 (0.00s)
=== RUN   TestQuoteIdentifier
--- PASS: TestQuoteIdentifier (0.00s)
=== RUN   TestCopyInStmt
--- PASS: TestCopyInStmt (0.00s)
=== RUN   TestCopyInSchemaStmt
--- PASS: TestCopyInSchemaStmt (0.00s)
=== RUN   TestCopyInMultipleValues
--- FAIL: TestCopyInMultipleValues (0.00s)
	copy_test.go:54: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyInRaiseStmtTrigger
--- FAIL: TestCopyInRaiseStmtTrigger (0.00s)
	conn_test.go:62: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyInTypes
--- FAIL: TestCopyInTypes (0.00s)
	copy_test.go:184: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyInWrongType
--- FAIL: TestCopyInWrongType (0.00s)
	copy_test.go:243: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyOutsideOfTxnError
--- FAIL: TestCopyOutsideOfTxnError (0.00s)
	copy_test.go:281: expected dial tcp [::1]:5432: getsockopt: connection refused, got dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyInBinaryError
--- FAIL: TestCopyInBinaryError (0.00s)
	copy_test.go:291: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyFromError
--- FAIL: TestCopyFromError (0.00s)
	copy_test.go:316: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopySyntaxError
--- FAIL: TestCopySyntaxError (0.00s)
	copy_test.go:341: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestCopyRespLoopConnectionError
--- FAIL: TestCopyRespLoopConnectionError (0.00s)
	copy_test.go:366: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestScanTimestamp
--- PASS: TestScanTimestamp (0.00s)
=== RUN   TestScanNilTimestamp
--- PASS: TestScanNilTimestamp (0.00s)
=== RUN   TestParseTs
--- PASS: TestParseTs (0.00s)
=== RUN   TestParseTsErrors
--- PASS: TestParseTsErrors (0.00s)
=== RUN   TestEncodeAndParseTs
--- FAIL: TestEncodeAndParseTs (0.01s)
	encode_test.go:124: 0: could not send value "22001-02-03 00:00:00 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 1: could not send value "2001-02-03 00:00:00 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 2: could not send value "2001-02-03 04:05:06 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 3: could not send value "2001-02-03 04:05:06.000001 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 4: could not send value "2001-02-03 04:05:06.00001 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 5: could not send value "2001-02-03 04:05:06.0001 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 6: could not send value "2001-02-03 04:05:06.001 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 7: could not send value "2001-02-03 04:05:06.01 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 8: could not send value "2001-02-03 04:05:06.1 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 9: could not send value "2001-02-03 04:05:06.12 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 10: could not send value "2001-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 11: could not send value "2001-02-03 04:05:06.1234 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 12: could not send value "2001-02-03 04:05:06.12345 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 13: could not send value "2001-02-03 04:05:06.123456 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 14: could not send value "2001-02-03 04:05:06.123 -0700 -0700" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 15: could not send value "2001-02-03 04:05:06 -0700 -0700" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 16: could not send value "2001-02-03 04:05:06 -0742 -0742" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 17: could not send value "2001-02-03 04:05:06 -0730 -0730" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 18: could not send value "2001-02-03 04:05:06 +0700 +0700" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 19: could not send value "-0010-02-03 04:05:06 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 20: could not send value "-0010-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 21: could not send value "-0010-02-03 04:05:06.123 -0700 -0700" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 22: could not send value "0001-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 23: could not send value "0000-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 24: could not send value "0000-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 25: could not send value "-0001-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 26: could not send value "-0001-02-03 04:05:06.123 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 27: could not send value "12345-02-03 04:05:06.1 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
	encode_test.go:124: 28: could not send value "123456-02-03 04:05:06.1 +0000 +0000" to the database: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestFormatTs
--- PASS: TestFormatTs (0.00s)
=== RUN   TestTimestampWithTimeZone
--- FAIL: TestTimestampWithTimeZone (0.00s)
	encode_test.go:177: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestTimestampWithOutTimezone
--- FAIL: TestTimestampWithOutTimezone (0.00s)
	encode_test.go:238: Could not run query: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestInfinityTimestamp
--- FAIL: TestInfinityTimestamp (0.01s)
	encode_test.go:298: Scanning -/+infinity, expected error to have prefix "sql: Scan error on column index 0: unsupported", got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:298: Scanning -/+infinity, expected error to have prefix "sql: Scan error on column index 0: unsupported", got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:298: Scanning -/+infinity, expected error to have prefix "sql: Scan error on column index 0: unsupported", got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:298: Scanning -/+infinity, expected error to have prefix "sql: Scan error on column index 0: unsupported", got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:306: Scanning -/+infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:310: Scanning -/+infinity, expected []byte, got <nil>
	encode_test.go:313: Scanning -/+infinity, expected "-infinity", got ""
	encode_test.go:306: Scanning -/+infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:310: Scanning -/+infinity, expected []byte, got <nil>
	encode_test.go:313: Scanning -/+infinity, expected "-infinity", got ""
	encode_test.go:306: Scanning -/+infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:310: Scanning -/+infinity, expected []byte, got <nil>
	encode_test.go:313: Scanning -/+infinity, expected "infinity", got ""
	encode_test.go:306: Scanning -/+infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:310: Scanning -/+infinity, expected []byte, got <nil>
	encode_test.go:313: Scanning -/+infinity, expected "infinity", got ""
	encode_test.go:323: Scanning infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:326: Scanning infinity, expected "2500-01-01 00:00:00 +0000 UTC", got "0001-01-01 00:00:00 +0000 UTC"
	encode_test.go:331: Scanning infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:334: Scanning Infinity, expected time "2500-01-01 00:00:00 +0000 UTC", got "0001-01-01 00:00:00 +0000 UTC"
	encode_test.go:339: Scanning -infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:342: Scanning -infinity, expected time "1500-01-01 00:00:00 +0000 UTC", got "0001-01-01 00:00:00 +0000 UTC"
	encode_test.go:347: Scanning -infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:350: Scanning -infinity, expected time "1500-01-01 00:00:00 +0000 UTC", got "0001-01-01 00:00:00 +0000 UTC"
	encode_test.go:358: Encoding -infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:361: Encoding -infinity, expected "-infinity", got ""
	encode_test.go:365: Encoding -infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:368: Encoding -infinity, expected "-infinity", got ""
	encode_test.go:373: Encoding infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:376: Encoding infinity, expected "infinity", got ""
	encode_test.go:380: Encoding infinity, expected no error, got "dial tcp [::1]:5432: getsockopt: connection refused"
	encode_test.go:383: Encoding infinity, expected "infinity", got ""
=== RUN   TestStringWithNul
--- PASS: TestStringWithNul (0.00s)
=== RUN   TestByteSliceToText
--- FAIL: TestByteSliceToText (0.00s)
	encode_test.go:422: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestStringToBytea
--- FAIL: TestStringToBytea (0.00s)
	encode_test.go:440: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestTextByteSliceToUUID
--- FAIL: TestTextByteSliceToUUID (0.00s)
	encode_test.go:466: dial tcp [::1]:5432: getsockopt: connection refused
=== RUN   TestBinaryByteSlicetoUUID
--- FAIL: TestBinaryByteSlicetoUUID (0.00s)
panic: interface conversion: error is *net.OpError, not *pq.Error [recovered]
	panic: interface conversion: error is *net.OpError, not *pq.Error

goroutine 594 [running]:
panic(0x67ae60, 0xc42024c880)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4200dd200)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x67ae60, 0xc42024c880)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/mainflux/mainflux/vendor/github.com/lib/pq.TestBinaryByteSlicetoUUID(0xc4200dd200)
	/home/drasko/go/src/github.com/mainflux/mainflux/vendor/github.com/lib/pq/encode_test.go:497 +0x5ae
testing.tRunner(0xc4200dd200, 0x6e2370)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2ec
FAIL	github.com/mainflux/mainflux/vendor/github.com/lib/pq	0.057s
=== RUN   TestHstore
--- SKIP: TestHstore (0.02s)
	hstore_test.go:42: Skipping hstore tests - hstore extension create failed: dial tcp [::1]:5432: getsockopt: connection refused
PASS
ok  	github.com/mainflux/mainflux/vendor/github.com/lib/pq/hstore	0.020s
?   	github.com/mainflux/mainflux/vendor/github.com/lib/pq/listen_example	[no test files]
?   	github.com/mainflux/mainflux/vendor/github.com/lib/pq/oid	[no test files]
drasko@Lenin:~/go/src/github.com/mainflux/mainflux/vendor/github.com/lib/pq$ 
```

**Comment by uhoh-itsmaciek** [comment]
It looks like you're failing to connect to Postgres during the test run--have you configured [environment variables](https://github.com/lib/pq/#tests) with the required connection info? Tests run fine here on current `master`.

**Comment by drasko** [comment]
Yep, I am not connecting to Postgress at all...
