### ISSUE TITLE
Panic on simple query

### ISSUE THREAD

**Issue by GSokol** [lib/pq#809]
The string like
```go
rows, err := s.pg.QueryContext(ctx, query)
```
sometimes causes
```
Recover after panic: runtime error: invalid memory address or nil pointer dereference
goroutine 12820 [running]:
runtime/debug.Stack(0xc4207fea60, 0x9493e0, 0xef50d0)
    /usr/lib/go-1.9/src/runtime/debug/stack.go:24 +0xa7
GSokol/gotestproj/middlewares.(*LogMiddleware).Log.func1.1(0xc42086db30)
    /go/src/GSokol/gotestproj/middlewares/log.go:46 +0x60
panic(0x9493e0, 0xef50d0)
    /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
GSokol/gotestproj/vendor/github.com/lib/pq.(*conn).QueryContext(0xc4203a0dc0, 0xf09f40, 0xc42086dd10, 0xc42006d080, 0x15a, 0xf59ea0, 0x0, 0x0, 0x939ac0, 0xc42001e000, ...)
    /go/src/GSokol/gotestproj/vendor/github.com/lib/pq/conn_go18.go:28 +0x273
```

```
revision = "90697d60dd844d5ef6ff15135d0203f65d2f53b8"
```

**Comment by GSokol** [comment]
Than was caused by pgbouncer bug https://github.com/pgbouncer/pgbouncer/issues/223
